import {expect,test} from '@playwright/test';
test('practice Run captures exact submitted code without incrementing attempts',async({page,request})=>{
 const before=await(await request.get('/api/progress')).json();await page.goto('/practice/start-001');await expect(page.locator('.monaco-editor textarea')).toBeVisible();const code='result = 1 / 0\n# actual practice Run capture';await page.locator('.monaco-editor textarea').click({force:true});await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(code);await page.getByRole('button',{name:'Запустить',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('koda:run-observations:v1:anonymous')||'[]')[0]?.code)).toBe(code);
 const record=await page.evaluate(()=>JSON.parse(localStorage.getItem('koda:run-observations:v1:anonymous')||'[]')[0]);expect(record.source).toBe('practice-run');expect(record.feedback.error_type).toBe('ZeroDivisionError');await page.goto(`/errors?record=run:${record.id}`);await expect(page.locator('.history-code')).toHaveText(code);await expect(page.locator('.history-message').filter({hasText:'division by zero'})).toContainText('division by zero');const after=await(await request.get('/api/progress')).json();expect(after.attempts).toBe(before.attempts);
});
test('sandbox failure reaches contextual history as exact local code without a task attempt',async({page,request})=>{
 test.setTimeout(180000);const before=await(await request.get('/api/progress')).json();await page.goto('/sandbox');await expect(page.locator('.sandbox-runtime.ready')).toContainText('Python готов',{timeout:120000});const code='raise ValueError("QA_SANDBOX_CAPTURE")\n# exact original';await page.locator('.monaco-editor textarea').click({force:true});await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(code);await page.getByRole('button',{name:'Запустить',exact:true}).click();await expect(page.locator('.sandbox-traceback')).toContainText('QA_SANDBOX_CAPTURE');
 await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('koda:run-observations:v1:anonymous')||'[]')[0]?.code)).toBe(code);const record=await page.evaluate(()=>JSON.parse(localStorage.getItem('koda:run-observations:v1:anonymous')||'[]')[0]);expect(record.source).toBe('sandbox-run');await page.goto(`/errors?record=run:${record.id}`);await expect(page.locator('.history-code')).toHaveText(code);await expect(page.getByRole('link',{name:'Открыть песочницу →'})).toHaveAttribute('href','/sandbox');const after=await(await request.get('/api/progress')).json();expect(after.attempts).toBe(before.attempts);
});
