import { expect,test,type Page } from '@playwright/test';
async function evidence(page:Page){return page.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(key=>key.startsWith('koda:achievements:')||key.startsWith('koda:study-interval:')).sort().map(key=>[key,localStorage.getItem(key)])));}
async function bounded(page:Page,selector:string,width:number){for(const rect of await page.locator(selector).evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return{left:r.left,right:r.right,width:r.width};}).filter(r=>r.width>0))){expect(rect.left).toBeGreaterThanOrEqual(-1);expect(rect.right).toBeLessThanOrEqual(width+1);}expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);}
for(const width of [1280,1440,390]){
 test(`contextual home and knowledge preserve evidence and valid navigation at ${width}px`,async({page,request})=>{
  await page.setViewportSize({width,height:900});await page.goto('/');const support=page.getByRole('complementary',{name:'Поддержка обучения'});await expect(support).toBeVisible();await expect(support).toContainText('Полученные достижения появятся здесь.');
  const before=await evidence(page);const homeBoxes=await page.locator('.dashboard-main-column,.home-support-column').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));
  if(width>1000){expect(homeBoxes[1].width).toBeCloseTo(280,0);expect(homeBoxes[1].left).toBeGreaterThan(homeBoxes[0].right);}else expect(homeBoxes[1].top).toBeGreaterThanOrEqual(homeBoxes[0].bottom-1);
  await bounded(page,'.dashboard-main-column,.home-support-column,.home-support-column a,.home-support-column button',width);
  await expect(page.getByRole('button',{name:'Продолжить практику →',exact:true})).toBeVisible();await expect(support.getByRole('link').first()).toHaveAttribute('href',/^\/topics\//);
  const contrast=await page.locator('.dashboard-mockup .stat strong').evaluateAll(nodes=>nodes.map(n=>{const luminance=(value:string)=>{const c=(value.match(/\d+/g)||[]).slice(0,3).map(Number).map(x=>{const s=x/255;return s<=.04045?s/12.92:((s+.055)/1.055)**2.4;});return c[0]*.2126+c[1]*.7152+c[2]*.0722;};let parent=n.parentElement!;while(parent.parentElement&&getComputedStyle(parent).backgroundColor==='rgba(0, 0, 0, 0)')parent=parent.parentElement;const a=luminance(getComputedStyle(n).color),b=luminance(getComputedStyle(parent).backgroundColor);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);}));for(const value of contrast)expect(value).toBeGreaterThanOrEqual(4.5);
  await page.screenshot({path:`reports/qa-context-home-${width}.png`,fullPage:true});expect(await evidence(page)).toEqual(before);
  const units=await (await request.get('/api/knowledge')).json();const unit=units.find((u:{article:{sections:unknown[]};cheatSheet:{entries:unknown[]}})=>u.article.sections.length&&u.cheatSheet.entries.length);
  await page.goto('/knowledge/'+unit.slug);const nav=page.getByRole('complementary',{name:'Навигация по материалу'});await expect(nav).toBeVisible();await page.getByRole('button',{name:'Статья',exact:true}).click();
  for(const link of await nav.locator('a[href^="#"]').all()){const href=await link.getAttribute('href');expect(await page.locator('[id]').evaluateAll((nodes,id)=>nodes.some(n=>n.id===id),href!.slice(1))).toBe(true);}
  for(const link of await nav.locator('a[href^="/knowledge/"]').all()){const href=await link.getAttribute('href');const other=units.find((u:{slug:string})=>'/knowledge/'+u.slug===href);expect(other).toBeTruthy();expect(other.category).toBe(unit.category);expect(other.id).not.toBe(unit.id);}
  const boxes=await page.locator('.knowledge-main-column,.knowledge-context-column').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));if(width>1000){expect(boxes[1].left).toBeGreaterThan(boxes[0].right);expect(boxes[1].width).toBeCloseTo(240,0);}else expect(boxes[1].top).toBeGreaterThanOrEqual(boxes[0].bottom-1);
  await bounded(page,'.knowledge-main-column,.knowledge-context-column,.knowledge-context-column a',width);await page.screenshot({path:`reports/qa-context-article-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Шпаргалка',exact:true}).click();await expect(nav.locator('a[href^="#cheat-group-"]')).not.toHaveCount(0);await bounded(page,'.knowledge-main-column,.knowledge-context-column,.cheat-table',width);await page.screenshot({path:`reports/qa-context-cheat-${width}.png`,fullPage:true});expect(await evidence(page)).toEqual(before);
  await page.evaluate(()=>{const s={events:[],unlocked:{first_task:{unlockedAt:'2026-10-08T12:00:00Z',sourceEventId:'qa-context-fixture',xp:50,seen:true,celebrated:true}},activeCosmetics:{},backfillVersion:2,timezone:'UTC'};localStorage.setItem('koda:achievements:v1',JSON.stringify(s));});await page.goto('/');await expect(page.locator('.home-latest-award .achievement-art')).toBeVisible();const seeded=await evidence(page);await page.reload();await expect(page.locator('.home-latest-award .achievement-art')).toBeVisible();expect(await evidence(page)).toEqual(seeded);
 });
 test(`wide working pages fill available space without overflow at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});for(const [url,selector] of [['/practice/start-001','.practice'],['/sandbox','.sandbox-page'],['/progress','.compact-progress .page'],['/achievements','.achievement-room']]){await page.goto(url);await expect(page.locator(selector).first()).toBeVisible();await bounded(page,selector,width);
   const geometry=await page.locator(selector).first().evaluate(n=>{const r=n.getBoundingClientRect(),main=document.querySelector('.compact-app > .compact-main')!,m=main.getBoundingClientRect(),s=getComputedStyle(main);return{left:r.left,right:r.right,mainLeft:m.left+parseFloat(s.paddingLeft),mainRight:m.right-parseFloat(s.paddingRight)};});expect(Math.abs(geometry.left-geometry.mainLeft)).toBeLessThanOrEqual(2);expect(Math.abs(geometry.right-geometry.mainRight)).toBeLessThanOrEqual(2);await page.screenshot({path:`reports/qa-context-${url.split('/')[1]}-${width}.png`,fullPage:true});}
 });
}
