import {expect,test,type Page} from '@playwright/test';
async function bounds(page:Page,width:number){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);for(const box of await page.locator('.context-aside,.context-main,.history-code').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return{left:r.left,right:r.right};}))){expect(box.left).toBeGreaterThanOrEqual(-1);expect(box.right).toBeLessThanOrEqual(width+1);}}
for(const width of [1280,1440,390])test(`real failure detail and functional right columns ${width}`,async({page,request})=>{
 await page.setViewportSize({width,height:900});
 const code=`result = 1 / 0\n# independent-context-${width}`;
 const submitted=await request.post('/api/attempts/submit',{data:{exercise_id:'start-001',code}});expect(submitted.ok()).toBe(true);expect((await submitted.json()).passed).toBe(false);
 const history=await(await request.get('/api/attempts/history')).json();const id=history.items[0].id;
 const initialProgress=await(await request.get('/api/progress')).json();
 await page.goto(`/errors?record=attempt:${id}`);await expect(page.locator('.history-code')).toHaveText(code);await expect(page.locator('.history-message').filter({hasText:'division by zero'})).toContainText('division by zero');const side=page.getByRole('complementary',{name:'Помощь с ошибкой'});await expect(side.getByRole('link',{name:'Открыть задачу →'})).toHaveAttribute('href','/practice/start-001');await expect(side.getByRole('button',{name:'Восстановить код'})).toBeVisible();await bounds(page,width);await page.screenshot({path:`reports/qa-functional-errors-${width}.png`,fullPage:true});
 await side.getByRole('link',{name:'Открыть задачу →'}).click();await expect(page.locator('.monaco-editor textarea')).toBeVisible();await page.locator('.monaco-editor textarea').click({force:true});await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('result = 777 # current valuable draft');await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('koda:task-state:v1')||'{}').tasks?.['start-001']?.code)).toBe('result = 777 # current valuable draft');
 await page.goto(`/profile/history?record=attempt:${id}`);await expect(page.locator('.history-code')).toHaveText(code);await page.getByRole('button',{name:'Восстановить код'}).click();await expect(page.getByRole('alert')).toContainText('Текущий черновик отличается');await page.getByRole('button',{name:'Заменить черновик'}).click();await expect(page).toHaveURL(/\/practice\/start-001/);await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('koda:task-state:v1')||'{}').tasks?.['start-001']?.code)).toBe(code);
 await page.goto('/profile/history');await expect(page.getByRole('complementary',{name:'Действия с записью'})).toBeVisible();await page.getByRole('combobox',{name:'Результат',exact:true}).selectOption('failed');await expect(page.locator('.history-detail')).toBeVisible();await bounds(page,width);await page.screenshot({path:`reports/qa-functional-history-${width}.png`,fullPage:true});
 await page.goto('/progress');const steps=page.getByRole('complementary',{name:'Следующие шаги'});await expect(steps).toBeVisible();await expect(steps.getByRole('link',{name:'Продолжить практику →'})).toHaveAttribute('href',/^\/practice\//);await expect(page.getByLabel('Измеренное время занятий за семь дней')).toBeVisible();await bounds(page,width);await page.screenshot({path:`reports/qa-functional-progress-${width}.png`,fullPage:true});
 const afterProgress=await(await request.get('/api/progress')).json();expect(afterProgress.attempts).toBe(initialProgress.attempts);expect(afterProgress.solved_ids).toEqual(initialProgress.solved_ids);
});
