import { expect, test, type Page } from '@playwright/test';
import fs from 'node:fs';
const manifest=JSON.parse(fs.readFileSync('apps/web/public/achievements/manifest.json','utf8'));
const timer=(page:Page)=>page.locator('.study-session-control');
async function localSeconds(page:Page){return page.evaluate(()=>{const intervals=[] as Array<[number,number]>;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(!key.startsWith('koda:study-interval:v1:anonymous:'))continue;const row=JSON.parse(localStorage.getItem(key)!);intervals.push([Date.parse(row.payload.start),Date.parse(row.payload.end)]);}intervals.sort((a,b)=>a[0]-b[0]);let total=0,end=-Infinity;for(const [start,stop] of intervals){total+=Math.max(0,stop-Math.max(start,end));end=Math.max(end,stop);}return total/1000;});}
async function bounded(page:Page,width:number,selector:string){for(const box of await page.locator(selector).evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return{left:r.left,right:r.right,width:r.width,height:r.height};}))){expect(box.left).toBeGreaterThanOrEqual(-1);expect(box.right).toBeLessThanOrEqual(width+1);}}
test('desktop trophies remain anchored above their shelf and table surfaces',async({page})=>{
 await page.setViewportSize({width:1280,height:900});await page.goto('/achievements');await expect(page.locator('.room-trophy')).toHaveCount(10);
 const anchors=await page.locator('.room-trophy').evaluateAll(nodes=>nodes.map(node=>{const box=node.getBoundingClientRect(),room=node.parentElement!.getBoundingClientRect(),style=getComputedStyle(node),art=node.querySelector(".achievement-art")!.getBoundingClientRect();return{artWidth:art.width,objectWidth:box.width,support:(art.top+.9*art.height-room.top)/room.height,transform:style.transform,anchor:parseFloat(style.getPropertyValue('--room-y'))/100,base:(box.bottom-room.top)/room.height,center:(box.left+box.width/2-room.left)/room.width,x:parseFloat(style.getPropertyValue('--room-x'))/100};}));
 for(const anchor of anchors){expect(Math.abs(anchor.artWidth-anchor.objectWidth)).toBeLessThan(1);expect(Math.abs(anchor.support-anchor.anchor)).toBeLessThan(.005);expect(anchor.transform).not.toBe('none');expect(Math.abs(anchor.center-anchor.x)).toBeLessThan(.005);expect(anchor.base-anchor.anchor).toBeGreaterThanOrEqual(-.015);expect(anchor.base-anchor.anchor).toBeLessThan(.04);}
 await page.locator('.room-clock').hover();expect(await page.locator('.room-clock').evaluate(node=>getComputedStyle(node).transform)).not.toBe('none');
});
for(const width of[1280,390]){
 test(`manual study timer preserves pause, navigation and reload at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});await page.goto('/');await expect(timer(page).getByRole('button',{name:'Начать занятие',exact:true})).toBeVisible();
  await timer(page).getByRole('button',{name:'Начать занятие',exact:true}).click();await expect(timer(page)).toContainText('Занятие идёт');await page.waitForTimeout(2100);await timer(page).getByRole('button',{name:'Пауза',exact:true}).click();
  const paused=await timer(page).locator('b').innerText();const initial=await localSeconds(page);expect(initial).toBeGreaterThanOrEqual(2);expect(initial).toBeLessThan(6);await page.waitForTimeout(1500);expect(await timer(page).locator('b').innerText()).toBe(paused);expect(await localSeconds(page)).toBe(initial);
  await timer(page).getByRole('button',{name:'Продолжить',exact:true}).click();if(width===390)await page.getByRole('button',{name:'Открыть меню',exact:true}).click();await page.getByRole('link',{name:'Прогресс',exact:true}).click();await expect(page).toHaveURL(/\/progress$/);await expect(timer(page)).toContainText('Занятие идёт');await page.waitForTimeout(1100);await timer(page).getByRole('button',{name:'Пауза',exact:true}).click();
  const beforeReload=await localSeconds(page);expect(beforeReload).toBeGreaterThan(initial);const savedClock=await timer(page).locator('b').innerText();await page.reload();await expect(timer(page)).toContainText('На паузе');expect(await timer(page).locator('b').innerText()).toBe(savedClock);expect(await localSeconds(page)).toBe(beforeReload);
  await expect(page.getByRole('heading',{name:'Время занятий · по таймеру',exact:true})).toBeVisible();await expect(page.locator('.study-time-summary')).toContainText('менее минуты');const contrasts=await page.locator('.study-time-summary strong').evaluateAll(nodes=>{const luminance=(value:string)=>{const channels=(value.match(/\d+/g)||[]).slice(0,3).map(x=>Number(x)/255).map(x=>x<=0.04045?x/12.92:((x+0.055)/1.055)**2.4);return channels[0]*0.2126+channels[1]*0.7152+channels[2]*0.0722;};const bg=luminance(getComputedStyle(document.body).backgroundColor);return nodes.map(node=>{const fg=luminance(getComputedStyle(node).color);return(Math.max(fg,bg)+0.05)/(Math.min(fg,bg)+0.05);});});contrasts.forEach(value=>expect(value).toBeGreaterThanOrEqual(4.5));await timer(page).getByRole('button',{name:'Завершить',exact:true}).click();await expect(timer(page)).toContainText('Занятие завершено');expect(await localSeconds(page)).toBe(beforeReload);await bounded(page,width,'.study-session-control, .study-session-control button, .study-time-summary');await page.screenshot({path:`reports/qa-study-time-${width}.png`,fullPage:true});
 });
 test(`ivory room keeps locked and advanced trophies accessible at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});await page.goto('/achievements');await expect(page.locator('.room-trophy')).toHaveCount(10);await expect(page.locator('.room-clock')).toHaveClass(/locked/);await expect(page.locator('.room-clock .achievement-art')).toHaveAttribute('data-tier','1');
  await bounded(page,width,'.achievement-room, .room-trophy');for(const box of await page.locator('.room-trophy').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()))){expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);}
  if(width===390){for(const transform of await page.locator('.room-trophy').evaluateAll(nodes=>nodes.map(node=>getComputedStyle(node).transform)))expect(transform).toBe('none');}
  expect(await page.locator('.achievement-room').evaluate(e=>getComputedStyle(e).backgroundImage)).toContain('ivory-room-v2.webp');await page.locator('.room-clock').focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.room-clock')).toBeFocused();await page.screenshot({path:`reports/qa-room-locked-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Вся коллекция',exact:true}).click();await expect(page.locator('.family-preview')).toHaveCount(51);
  const timeFamily=manifest.families.find((f:{slug:string})=>f.slug==='51_study_time');const ids=timeFamily.achievements.slice(0,2).map((x:{id:string})=>x.id);
  await page.evaluate(({ids})=>{const start='2026-10-08T10:00:00Z',end='2026-10-08T11:00:00Z';const interval={id:'room-qa-hour',sessionId:'room-qa',start,end,timezone:'UTC',schema:1};const event={eventId:'study_interval_recorded:room-qa-hour',type:'study_interval_recorded',payload:interval,occurredAt:end,localDate:'2026-10-08',version:1};const snapshot=JSON.parse(localStorage.getItem('koda:achievements:v1')||'{}');snapshot.events=[...(snapshot.events||[]),event];snapshot.unlocked=snapshot.unlocked||{};for(const id of ids)snapshot.unlocked[id]={unlockedAt:end,sourceEventId:event.eventId,xp:10,seen:true,celebrated:true};snapshot.activeCosmetics=snapshot.activeCosmetics||{};snapshot.backfillVersion=2;snapshot.timezone='UTC';localStorage.setItem('koda:achievements:v1',JSON.stringify(snapshot));localStorage.setItem('koda:study-interval:v1:anonymous:'+event.eventId,JSON.stringify(event));},{ids});
  await page.reload();await expect(page.locator('.room-clock')).toHaveClass(/earned/);await expect(page.locator('.room-clock .achievement-art')).toHaveAttribute('data-tier','2');await page.getByRole('button',{name:'Показать названия',exact:true}).click();await expect(page.locator('.room-trophy > span')).toHaveCount(10);await bounded(page,width,'.achievement-room, .room-trophy');await page.screenshot({path:`reports/qa-room-advanced-${width}.png`,fullPage:true});await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.room-trophy').first().evaluate(element=>getComputedStyle(element).transitionDuration)).toBe('0s');await page.evaluate(()=>{const nodes=[...document.querySelectorAll<HTMLElement>('.study-session-clock small,.study-session-clock b,.study-session-control button,.room-trophy span,.ach-head h1,.ach-section-head h2')];const sizes=nodes.map(node=>parseFloat(getComputedStyle(node).fontSize));nodes.forEach((node,index)=>{node.style.fontSize=`${sizes[index]*2}px`;});});await bounded(page,width,'.achievement-room, .room-trophy, .room-trophy span, .study-session-control, .study-session-control button');await page.screenshot({path:`reports/qa-room-zoom-${width}.png`,fullPage:true});
 });
}

test('real header auto-pauses hidden activity and prevents a second visible tab owning the timer',async({page,context})=>{
 await page.goto('/');await timer(page).getByRole('button',{name:'Начать занятие',exact:true}).click();await page.waitForTimeout(1100);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await expect(timer(page)).toContainText('На паузе');const paused=await localSeconds(page);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(1100);expect(await localSeconds(page)).toBe(paused);await expect(timer(page)).toContainText('На паузе');
 const other=await context.newPage();await other.addInitScript(()=>Object.defineProperty(document,'hidden',{configurable:true,value:false}));await other.goto('/');await timer(page).getByRole('button',{name:'Продолжить',exact:true}).click();await expect(timer(page)).toContainText('Занятие идёт');
 await timer(other).getByRole('button',{name:'Продолжить',exact:true}).click();await expect(timer(other).getByRole('status')).toContainText('другой вкладке');await expect(timer(other)).toContainText('На паузе');await expect(timer(page)).toContainText('Занятие идёт');
 await timer(page).getByRole('button',{name:'Пауза',exact:true}).click();await timer(other).getByRole('button',{name:'Продолжить',exact:true}).click();await expect(timer(other)).toContainText('Занятие идёт');await page.waitForTimeout(1100);await timer(other).getByRole('button',{name:'Завершить',exact:true}).click();await expect(timer(other)).toContainText('Занятие завершено');expect(await localSeconds(other)).toBeGreaterThan(paused);await other.close();
});

test('real header reports storage failure without inventing study evidence',async({page})=>{
 await page.goto('/');await expect(timer(page)).toBeVisible();await page.evaluate(()=>{const original=Storage.prototype.setItem;Object.defineProperty(window,'qaOriginalStorageSet',{configurable:true,value:original});Storage.prototype.setItem=function(key,value){if(key.startsWith('koda:study-'))throw new DOMException('quota','QuotaExceededError');return original.call(this,key,value);};});
 await timer(page).getByRole('button',{name:'Начать занятие',exact:true}).click();await expect(timer(page).getByRole('status')).toContainText('Не удалось сохранить время');expect(await localSeconds(page)).toBe(0);await expect(timer(page).locator('b')).toHaveText('00:00:00');
 await page.evaluate(()=>{Storage.prototype.setItem=(window as unknown as {qaOriginalStorageSet:typeof Storage.prototype.setItem}).qaOriginalStorageSet;});await timer(page).getByRole('button',{name:'Продолжить',exact:true}).click();await page.waitForTimeout(1100);await timer(page).getByRole('button',{name:'Завершить',exact:true}).click();expect(await localSeconds(page)).toBeGreaterThanOrEqual(1);
});
