import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Sandbox } from "./Sandbox";
import type { SandboxResult } from "./sandbox-runtime";

let files = [{id:"f1",name:"sales.csv",logicalPath:"/datasets/sales.csv",sizeBytes:24,mimeType:"text/csv",createdAt:"now",updatedAt:"now",version:"hash"}];
const apiMock=vi.fn((path:string,init?:RequestInit)=>{if(path==="/sandbox/files")return Promise.resolve(files);if(init?.method==="PATCH"){files=[{...files[0],name:"new.csv",logicalPath:"/datasets/new.csv"}];return Promise.resolve(files[0])}if(init?.method==="DELETE"){files=[];return Promise.resolve(undefined)}return Promise.resolve({})});
const apiResponseMock=vi.fn((_path:string)=>Promise.resolve({arrayBuffer:()=>Promise.resolve(new ArrayBuffer(4))}));
vi.mock("./api",()=>({api:(path:string,init?:RequestInit)=>apiMock(path,init),apiResponse:(path:string)=>apiResponseMock(path)}));
vi.mock("./auth",()=>({getAccessToken:()=>"token"}));
const terminate=vi.fn(),inspect=vi.fn<()=>Promise<{imports:string[];datasets:string[]}>>(()=>Promise.resolve({imports:[],datasets:[]})),run=vi.fn<()=>Promise<SandboxResult>>(()=>Promise.resolve({ok:true,stdout:"",plots:[],result:{kind:"dataframe",columns:["city"],index:["0"],data:[["Москва"]],shape:[1,1]}}));
const mountedPaths=new Set<string>();
vi.mock("./sandbox-runtime",()=>({SandboxRuntime:class{ready(){return Promise.resolve({version:"0.27.7",metrics:{workerCreatedMs:1,pyodideReadyMs:2,packagesReadyMs:3}})}async run(_code:string,_files:unknown[],loader:(paths:string[])=>Promise<unknown>){const paths=(await inspect()).datasets.filter(path=>!mountedPaths.has(path));if(paths.length){await loader(paths);paths.forEach(path=>mountedPaths.add(path))}return run()}terminate(){terminate()}}}));
vi.mock("@monaco-editor/react",()=>({default:({value,onChange}:{value:string;onChange:(value:string)=>void})=><textarea aria-label="Редактор Python" value={value} onChange={e=>onChange(e.target.value)}/> }));

class FakeXHR{
  static last:FakeXHR;upload:{onprogress?:(event:{lengthComputable:boolean;loaded:number;total:number})=>void}={};status=201;responseText=JSON.stringify(files[0]);onload?:()=>void;onerror?:()=>void;
  constructor(){FakeXHR.last=this}open(){}setRequestHeader(){}send(){this.upload.onprogress?.({lengthComputable:true,loaded:1,total:1});this.onload?.()}
}

const renderSandbox=()=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Sandbox/></QueryClientProvider>);
describe("sandbox",()=>{
  afterEach(()=>{mountedPaths.clear();cleanup()});
  beforeEach(()=>{files=[{id:"f1",name:"sales.csv",logicalPath:"/datasets/sales.csv",sizeBytes:24,mimeType:"text/csv",createdAt:"now",updatedAt:"now",version:"hash"}];localStorage.clear();apiMock.mockClear();apiResponseMock.mockClear();inspect.mockReset().mockResolvedValue({imports:[],datasets:[]});run.mockReset().mockResolvedValue({ok:true,stdout:"",plots:[],result:{kind:"dataframe",columns:["city"],index:["0"],data:[["Москва"]],shape:[1,1]}});terminate.mockClear();vi.stubGlobal("XMLHttpRequest",FakeXHR);Object.assign(navigator,{clipboard:{writeText:vi.fn().mockResolvedValue(undefined)}})});
  it("shows files and copies the logical path",async()=>{renderSandbox();expect(await screen.findByText("/datasets/sales.csv")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/Путь/}));expect(navigator.clipboard.writeText).toHaveBeenCalledWith("/datasets/sales.csv")});
  it("runs only with Ctrl+Enter and leaves plain Enter to the editor",async()=>{renderSandbox();const editor=await screen.findByLabelText("Редактор Python");fireEvent.change(editor,{target:{value:"df.head()"}});expect(localStorage.getItem("koda:sandbox-code:v1")).toBe("df.head()");fireEvent.keyDown(editor,{key:"Enter"});expect(run).not.toHaveBeenCalled();fireEvent.keyDown(editor,{key:"Enter",ctrlKey:true});await waitFor(()=>expect(run).toHaveBeenCalledTimes(1));expect(await screen.findByText("Москва")).toBeInTheDocument()});
  it("renders a successful value, stdout and the measured execution time",async()=>{run.mockResolvedValueOnce({ok:true,stdout:"KODA\n",plots:[],executionMs:18.4,result:{kind:"value",value:"2"}});renderSandbox();await screen.findByText(/Python готов/);fireEvent.click(screen.getByText("Запустить"));expect(await screen.findByText("2")).toBeInTheDocument();expect(screen.getByText("KODA")).toBeInTheDocument();expect(screen.getByText("Выполнено за 18 мс")).toBeInTheDocument();await new Promise(resolve=>requestAnimationFrame(()=>resolve(undefined)));expect(screen.getByText("2")).toBeInTheDocument()});
  it("renders an error and then the next successful result",async()=>{run.mockResolvedValueOnce({ok:false,stdout:"",plots:[],executionMs:4,errorType:"ZeroDivisionError",message:"division by zero",traceback:"Traceback"}).mockResolvedValueOnce({ok:true,stdout:"",plots:[],executionMs:3,result:{kind:"value",value:"10"}});renderSandbox();await screen.findByText(/Python готов/);fireEvent.click(screen.getByText("Запустить"));expect(await screen.findByText(/ZeroDivisionError/)).toBeInTheDocument();fireEvent.click(screen.getByText("Запустить"));expect(await screen.findByText("10")).toBeInTheDocument();expect(screen.queryByText(/ZeroDivisionError/)).not.toBeInTheDocument();expect(screen.getByText("Выполнено за 3 мс")).toBeInTheDocument()});
  it("blocks a duplicate Run while execution is pending",async()=>{let finish!:Parameters<PromiseConstructor["resolve"]>[0] extends never ? never : (value:any)=>void;run.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve}));renderSandbox();await screen.findByText(/Python готов/);const button=screen.getByText("Запустить");fireEvent.click(button);await waitFor(()=>expect(run).toHaveBeenCalledTimes(1));fireEvent.keyDown(screen.getByLabelText("Редактор Python"),{key:"Enter",ctrlKey:true});expect(run).toHaveBeenCalledTimes(1);finish({ok:true,stdout:"",plots:[],result:{kind:"value",value:"2"}});await screen.findByText("2")});
  it("downloads a referenced CSV once and reuses its mount",async()=>{inspect.mockResolvedValue({imports:["pandas"],datasets:["/datasets/sales.csv"]});renderSandbox();await screen.findByText(/Python готов/);fireEvent.click(screen.getByText("Запустить"));await waitFor(()=>expect(run).toHaveBeenCalledTimes(1));expect(apiResponseMock).toHaveBeenCalledWith("/sandbox/files/f1/content");apiResponseMock.mockClear();fireEvent.click(screen.getByText("Запустить"));await waitFor(()=>expect(run).toHaveBeenCalledTimes(2));expect(apiResponseMock).not.toHaveBeenCalled()});
  it("uploads a CSV and reports progress",async()=>{renderSandbox();const input=document.querySelector('input[type="file"]') as HTMLInputElement;fireEvent.change(input,{target:{files:[new File(["a,b\n1,2"],"new.csv",{type:"text/csv"})]}});await waitFor(()=>expect(FakeXHR.last).toBeTruthy());await waitFor(()=>expect(apiMock).toHaveBeenCalledWith("/sandbox/files",undefined))});
  it("renames and deletes after confirmation",async()=>{vi.stubGlobal("prompt",vi.fn(()=>"new.csv"));vi.stubGlobal("confirm",vi.fn(()=>true));renderSandbox();await screen.findByText("sales.csv");fireEvent.click(screen.getByText("Переименовать"));await waitFor(()=>expect(apiMock).toHaveBeenCalledWith("/sandbox/files/f1",expect.objectContaining({method:"PATCH"})));fireEvent.click(screen.getByText("Удалить"));await waitFor(()=>expect(apiMock).toHaveBeenCalledWith("/sandbox/files/f1",expect.objectContaining({method:"DELETE"})))});
  it("restarts the Python environment without clearing code",async()=>{renderSandbox();const editor=await screen.findByLabelText("Редактор Python");fireEvent.change(editor,{target:{value:"answer = 42"}});fireEvent.click(screen.getByText("Перезапустить среду"));expect(terminate).toHaveBeenCalled();expect((screen.getByLabelText("Редактор Python") as HTMLTextAreaElement).value).toBe("answer = 42")});
});
