import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AchievementsPage } from "./AchievementsPage";
import { clearAchievementManifestCache } from "./manifest";
vi.mock("../api",()=>({api:vi.fn().mockResolvedValue({solved_ids:[],modules:[],total:200})}));
vi.mock("./cloud",()=>({scheduleAchievementCloudSave:vi.fn()}));
const family=(slug:string,name:string,items:Array<[string,string]>)=>({slug,name,achievements:items.map(([id,title])=>({id,name:title,condition:`Условие ${title}`,rarity:"common",rarity_ru:"Обычная",xp:50,reward:"",icon:`icons/${id}.png`}))});
const manifest={version:"1",achievement_count:3,family_count:2,families:[family("tasks","Решённые задачи",[["first_task","Первопроходец"],["warmup","Разогрев"]]),family("streaks","Серия дней",[["streak_3","Первый ритм"]])]};
beforeEach(()=>{clearAchievementManifestCache();localStorage.clear();localStorage.setItem("koda:achievements:v1",JSON.stringify({events:[{eventId:"task_solved:a",type:"task_solved",payload:{taskId:"a"},occurredAt:"2026-08-12T00:00:00Z",localDate:"2026-08-12",version:1}],unlocked:{first_task:{unlockedAt:"2026-08-12T00:00:00Z",sourceEventId:"task_solved:a",xp:50,seen:true}},activeCosmetics:{},backfillVersion:1,timezone:"Europe/Moscow"}));vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:()=>Promise.resolve(manifest)}))});
afterEach(()=>{cleanup();vi.unstubAllGlobals()});
const open=async(client=new QueryClient({defaultOptions:{queries:{retry:false}}}))=>{render(<QueryClientProvider client={client}><AchievementsPage/></QueryClientProvider>);await screen.findByRole("button",{name:/Решённые задачи/});return client};
describe("achievement family screen",()=>{
  it("shows started families in overview and all families in full collection with decorative SVG artwork",async()=>{await open();expect(screen.getByRole("button",{name:"Главное"})).toHaveAttribute("aria-pressed","true");expect(screen.getAllByRole("button",{name:/Решённые задачи|Серия дней/})).toHaveLength(1);expect(screen.getByText("Первопроходец")).toBeInTheDocument();expect(screen.queryByText("Разогрев")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Вся коллекция"}));expect(screen.getAllByRole("button",{name:/Решённые задачи|Серия дней/})).toHaveLength(2);const artwork=document.querySelectorAll(".family-preview .achievement-art");expect(artwork).toHaveLength(2);for(const art of artwork){expect(art.tagName.toLowerCase()).toBe("svg");expect(art).toHaveAttribute("aria-hidden","true");}});
  it("includes a curated family even before it starts",async()=>{const curated={...manifest,families:[...manifest.families,family("07_sandbox","Песочница",[["sandbox_first","Первый запуск"]])]};vi.stubGlobal("fetch",vi.fn().mockResolvedValue({ok:true,json:()=>Promise.resolve(curated)}));await open();expect(screen.getByRole("button",{name:/Песочница/})).toBeInTheDocument();expect(screen.queryByRole("button",{name:/Серия дней/})).not.toBeInTheDocument();});
  it("does not render stages or detail before the family opens",async()=>{await open();expect(document.querySelectorAll(".family-step")).toHaveLength(0);fireEvent.click(screen.getByRole("button",{name:/Решённые задачи/}));expect(await screen.findByRole("dialog")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Первопроходец. Получено"})).toHaveClass("unlocked");expect(screen.getByRole("button",{name:"Разогрев. Следующая цель"})).toHaveClass("next")});
  it("filters locally without refetching",async()=>{await open();const calls=vi.mocked(fetch).mock.calls.length;fireEvent.click(screen.getByRole("button",{name:"Начатые"}));expect(screen.queryByRole("button",{name:/Серия дней/})).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Не начатые"}));await waitFor(()=>expect(screen.getByRole("button",{name:/Серия дней/})).toBeInTheDocument());expect(fetch).toHaveBeenCalledTimes(calls)});
  it("reuses the manifest cache after remount",async()=>{const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const first=render(<QueryClientProvider client={client}><AchievementsPage/></QueryClientProvider>);await screen.findByText("Первопроходец");first.unmount();render(<QueryClientProvider client={client}><AchievementsPage/></QueryClientProvider>);await screen.findByText("Первопроходец");expect(fetch).toHaveBeenCalledTimes(1)});
});
