import type { Rule } from "./types";
export const achievementRules: Record<string, Rule> = {
  first_task: { metric: "solved", target: 1 },
  warmup: { metric: "solved", target: 10 },
  working_set: { metric: "solved", target: 25 },
  fifty: { metric: "solved", target: 50 },
  three_digits: { metric: "solved", target: 100 },
  data_stream: { metric: "solved", target: 250 },
  compute_module: { metric: "solved", target: 500 },
  thousand: { metric: "solved", target: 1000 },
  streak_3: { metric: "maxStreak", target: 3 },
  streak_7: { metric: "maxStreak", target: 7 },
  streak_10: { metric: "maxStreak", target: 10 },
  streak_30: { metric: "maxStreak", target: 30 },
  streak_60: { metric: "maxStreak", target: 60 },
  streak_100: { metric: "maxStreak", target: 100 },
  streak_365: { metric: "maxStreak", target: 365 },
  first_module: { metric: "modules", target: 1 },
  three_modules: { metric: "modules", target: 3 },
  half_system: { metric: "halfModules", target: 1 },
  full_assembly: { metric: "allModules", target: 1 },
  no_empty_cell: { metric: "allTasks", target: 1 },
  absolute_coverage: { metric: "allTasks", target: 1 },
  first_run_solution: { metric: "firstTry", target: 1 },
  clean_streak: { metric: "cleanStreak", target: 5 },
  precise_line: { metric: "firstTry", target: 25 },
  flawless_module: { metric: "topic", topic: "flawless_module", target: 1 },
  no_hints: { metric: "noHints", target: 10 },
  independent_control: {
    metric: "topic",
    topic: "independent_control",
    target: 1,
  },
  second_pass: { metric: "topic", topic: "second_pass", target: 10 },
  error_intercept: { metric: "corrected", target: 1 },
  error_work: { metric: "corrected", target: 25 },
  debugger: { metric: "corrected", target: 100 },
  beyond_limits: { metric: "hardSolved", target: 1 },
  high_load: { metric: "hardSolved", target: 10 },
  red_zone: { metric: "hardSolved", target: 25 },
  expert_mode: { metric: "topic", topic: "hard_module", target: 1 },
  hard_complete: { metric: "topic", topic: "hard_course", target: 1 },
  first_execution: { metric: "sandboxRuns", target: 1 },
  sandbox_researcher: {
    metric: "composite",
    target: 1,
    requires: [
      { metric: "sandboxRuns", target: 25 },
      { metric: "sandboxDays", target: 3 },
    ],
  },
  laboratory: {
    metric: "composite",
    target: 1,
    requires: [
      { metric: "sandboxRuns", target: 100 },
      { metric: "sandboxDays", target: 10 },
    ],
  },
  own_data: { metric: "csvUploads", target: 1 },
  first_dataframe: { metric: "dataframes", target: 1 },
  multiple_sources: { metric: "joins", target: 1 },
  independent_project: { metric: "analyses", target: 1 },
  data_matrix: { metric: "topic", topic: "tabular_matrix", target: 1 },
  clean_dataset: { metric: "topic", topic: "data_cleaning", target: 1 },
  precise_selection: { metric: "topic", topic: "filtering", target: 1 },
  aggregation_master: { metric: "topic", topic: "aggregation", target: 1 },
  connector: { metric: "topic", topic: "table_joining", target: 1 },
  time_master: { metric: "topic", topic: "datetime", target: 1 },
  visual_signal: { metric: "charts", target: 1 },
  visualizer: { metric: "topic", topic: "visualization", target: 1 },
  data_researcher: { metric: "eda", target: 1 },
  junior_analyst: { metric: "allModules", target: 1 },
  data_analyst: {
    metric: "composite",
    target: 1,
    requires: [
      { metric: "modules", target: 20 },
      { metric: "projectScore", target: 70 },
    ],
  },
  koda_analyst: {
    metric: "composite",
    target: 1,
    requires: [
      { metric: "solved", target: 200 },
      { metric: "projectScore", target: 90 },
    ],
  },
  quick_start: { metric: "v2", target: 1 },
  short_loop: { metric: "v2", target: 1 },
  minimum_counts: { metric: "v2", target: 1 },
  comeback_2d: { metric: "v2", target: 2 },
  comeback_7d: { metric: "v2", target: 7 },
  comeback_30d: { metric: "v2", target: 30 },
  comeback_90d: { metric: "v2", target: 90 },
  rhythm_3_7: { metric: "v2", target: 3 },
  rhythm_10_30: { metric: "v2", target: 10 },
  rhythm_25_90: { metric: "v2", target: 25 },
  uneven_counts: { metric: "v2", target: 6 },
  clicked: { metric: "v2", target: 3 },
  try_again_2: { metric: "v2", target: 2 },
  try_again_4: { metric: "v2", target: 4 },
  try_again_7: { metric: "v2", target: 7 },
  self_debugger_runtime: { metric: "v2", target: 1 },
  clean_intercept: { metric: "v2", target: 1 },
  handrails_off: { metric: "v2", target: 5 },
  one_hint_enough: { metric: "v2", target: 1 },
  second_time_independent: { metric: "v2", target: 1 },
  hints_fading_1: { metric: "v2", target: 20 },
  hints_fading_2: { metric: "v2", target: 30 },
  hints_fading_3: { metric: "v2", target: 40 },
  error_with_patience: { metric: "v2", target: 1 },
  memory_echo_7: { metric: "v2", target: 7 },
  memory_echo_30: { metric: "v2", target: 30 },
  memory_echo_90: { metric: "v2", target: 90 },
  archive_open: { metric: "v2", target: 30 },
  weak_spot: { metric: "v2", target: 15 },
  breakthrough_mastery: { metric: "v2", target: 1 },
  cold_control: { metric: "v2", target: 1 },
  skill_three_forms: { metric: "v2", target: 3 },
  panorama_3: { metric: "v2", target: 3 },
  panorama_7: { metric: "v2", target: 7 },
  panorama_12: { metric: "v2", target: 12 },
  toolbelt_5: { metric: "v2", target: 5 },
  toolbelt_10: { metric: "v2", target: 10 },
  toolbelt_20: { metric: "v2", target: 20 },
  combo_session: { metric: "v2", target: 1 },
  what_if_3: { metric: "v2", target: 1 },
  what_if_10: { metric: "v2", target: 10 },
  what_if_25: { metric: "v2", target: 25 },
  controlled_explosion: { metric: "v2", target: 1 },
  reconnaissance: { metric: "v2", target: 1 },
  lesson_to_life: { metric: "v2", target: 1 },
  own_question: { metric: "v2", target: 1 },
  first_mini_analysis: { metric: "v2", target: 1 },
  no_loops_3: { metric: "v2", target: 3 },
  no_loops_10: { metric: "v2", target: 10 },
  no_loops_25: { metric: "v2", target: 25 },
  chain_reaction_3: { metric: "v2", target: 3 },
  chain_reaction_10: { metric: "v2", target: 10 },
  chain_reaction_25: { metric: "v2", target: 25 },
  not_by_sample: { metric: "v2", target: 1 },
  long_run_2m: { metric: "v2", target: 2 },
  long_run_4m: { metric: "v2", target: 4 },
  long_run_8m: { metric: "v2", target: 8 },
  long_run_12m: { metric: "v2", target: 12 },
  proven_by_time: { metric: "v2", target: 5 },
};
export const analystPath = [
  "first_task",
  "data_matrix",
  "clean_dataset",
  "precise_selection",
  "aggregation_master",
  "connector",
  "time_master",
  "visualizer",
  "data_researcher",
  "junior_analyst",
  "data_analyst",
  "koda_analyst",
] as const;
