import type{Rule}from'./types';
export const achievementRules:Record<string,Rule>={
 first_task:{metric:'solved',target:1},warmup:{metric:'solved',target:10},working_set:{metric:'solved',target:25},fifty:{metric:'solved',target:50},three_digits:{metric:'solved',target:100},data_stream:{metric:'solved',target:250},compute_module:{metric:'solved',target:500},thousand:{metric:'solved',target:1000},
 streak_3:{metric:'maxStreak',target:3},streak_7:{metric:'maxStreak',target:7},streak_10:{metric:'maxStreak',target:10},streak_30:{metric:'maxStreak',target:30},streak_60:{metric:'maxStreak',target:60},streak_100:{metric:'maxStreak',target:100},streak_365:{metric:'maxStreak',target:365},
 first_module:{metric:'modules',target:1},three_modules:{metric:'modules',target:3},half_system:{metric:'halfModules',target:1},full_assembly:{metric:'allModules',target:1},no_empty_cell:{metric:'allTasks',target:1},absolute_coverage:{metric:'allTasks',target:1},
 first_run_solution:{metric:'firstTry',target:1},clean_streak:{metric:'cleanStreak',target:5},precise_line:{metric:'firstTry',target:25},flawless_module:{metric:'topic',topic:'flawless_module',target:1},no_hints:{metric:'noHints',target:10},independent_control:{metric:'topic',topic:'independent_control',target:1},second_pass:{metric:'topic',topic:'second_pass',target:10},
 error_intercept:{metric:'corrected',target:1},error_work:{metric:'corrected',target:25},debugger:{metric:'corrected',target:100},
 beyond_limits:{metric:'hardSolved',target:1},high_load:{metric:'hardSolved',target:10},red_zone:{metric:'hardSolved',target:25},expert_mode:{metric:'topic',topic:'hard_module',target:1},hard_complete:{metric:'topic',topic:'hard_course',target:1},
 first_execution:{metric:'sandboxRuns',target:1},sandbox_researcher:{metric:'composite',target:1,requires:[{metric:'sandboxRuns',target:25},{metric:'sandboxDays',target:3}]},laboratory:{metric:'composite',target:1,requires:[{metric:'sandboxRuns',target:100},{metric:'sandboxDays',target:10}]},
 own_data:{metric:'csvUploads',target:1},first_dataframe:{metric:'dataframes',target:1},multiple_sources:{metric:'joins',target:1},independent_project:{metric:'analyses',target:1},
 data_matrix:{metric:'topic',topic:'tabular_matrix',target:1},clean_dataset:{metric:'topic',topic:'data_cleaning',target:1},precise_selection:{metric:'topic',topic:'filtering',target:1},aggregation_master:{metric:'topic',topic:'aggregation',target:1},connector:{metric:'topic',topic:'table_joining',target:1},time_master:{metric:'topic',topic:'datetime',target:1},
 visual_signal:{metric:'charts',target:1},visualizer:{metric:'topic',topic:'visualization',target:1},data_researcher:{metric:'eda',target:1},junior_analyst:{metric:'allModules',target:1},data_analyst:{metric:'composite',target:1,requires:[{metric:'modules',target:20},{metric:'projectScore',target:70}]},koda_analyst:{metric:'composite',target:1,requires:[{metric:'solved',target:200},{metric:'projectScore',target:90}]}
};
export const analystPath=['first_task','data_matrix','clean_dataset','precise_selection','aggregation_master','connector','time_master','visualizer','data_researcher','junior_analyst','data_analyst','koda_analyst'] as const;
