"""Individually authored executable references for source steps 1–92."""
REFERENCES = {
1: "result = orders.groupby('city').revenue.sum()",
2: "result = orders.groupby('channel').revenue.mean().round(2)",
3: "result = orders.groupby('manager').agg(order_count=('order_id','count'), total_revenue=('revenue','sum'), avg_revenue=('revenue','mean'))",
4: "result = orders.groupby(['city','category']).revenue.sum()",
5: "result = orders[orders.status == 'Оплачен'].groupby('city').revenue.sum()",
6: "result = orders.status.eq('Отменён').groupby(orders.channel).mean().mul(100).round(1)",
7: "counts = orders.groupby('customer_id').order_id.nunique()\nresult = counts[counts >= 2].sort_values(ascending=False)",
8: "totals = orders.groupby(['city','category']).revenue.sum().reset_index()\nresult = totals.loc[totals.groupby('city').revenue.idxmax()].reset_index(drop=True)",
9: "result = orders.groupby('category').rating.mean().round(2)",
10: "result = orders[orders.status == 'Оплачен'].groupby('city').delivery_days.mean().round(1)",
11: "result = orders.groupby('channel').is_new_customer.mean().mul(100).round(1)",
12: "result = orders.groupby('city').agg(order_count=('order_id','count'), total_revenue=('revenue','sum'), avg_revenue=('revenue','mean'), avg_delivery_days=('delivery_days','mean')).sort_values('total_revenue', ascending=False)",
13: "result = pd.read_csv(csv_path, parse_dates=['order_date'])",
14: "result = orders.shape",
15: "result = orders.head(5)",
16: "result = orders.tail(3)",
17: "missing = orders.isna().sum()\nresult = missing[missing > 0]",
18: "result = orders[['order_date','city','category','revenue']]",
19: "result = orders[orders.revenue > 20000]",
20: "result = orders[orders.city.isin(['Москва','Тула'])]",
21: "result = orders[(orders.rating == 5) & (orders.revenue > 10000)]",
22: "result = orders[orders.status != 'Оплачен']",
23: "result = orders.sort_values('revenue', ascending=False).head(5)",
24: "result = orders.sort_values('delivery_days', ascending=False)",
25: "result = orders.sort_values(['city','revenue'], ascending=[True,False])",
26: "result = orders.loc[orders.groupby('city').revenue.idxmin()]",
27: "result = orders.sort_values('order_date', ascending=False).head(10)",
28: "result = orders.assign(revenue_before_discount=orders.revenue + orders.discount)",
29: "result = orders.assign(is_large_order=orders.revenue >= 15000)",
30: "result = orders.assign(order_size=pd.cut(orders.revenue, bins=[-float('inf'),7000,15000,float('inf')], right=False, labels=['Небольшой','Средний','Крупный']))",
31: "result = orders.assign(revenue_per_item=orders.revenue / orders.quantity)",
32: "result = orders.assign(is_slow_delivery=orders.delivery_days > 3)",
33: "result = orders.assign(city_revenue=orders.groupby('city').revenue.transform('sum'))",
34: "result = (orders.revenue / orders.groupby('city').revenue.transform('sum') * 100).round(2)",
35: "result = orders.revenue - orders.groupby('channel').revenue.transform('mean')",
36: "result = orders.assign(avg_city_delivery=orders.groupby('city').delivery_days.transform('mean'))",
37: "result = orders[orders.revenue > orders.groupby('category').revenue.transform('mean')]",
38: "result = orders.isna().sum()",
39: "result = orders[orders.rating.isna()]",
40: "result = orders.assign(rating=orders.rating.fillna(0))",
41: "result = orders.rating.isna().groupby(orders.channel).mean().mul(100).round(1)",
42: "result = orders[orders[['order_id','customer_id','order_date','city','revenue']].isna().any(axis=1)]",
43: "result = orders[orders.duplicated('order_id', keep=False)]",
44: "result = orders[orders.duplicated(keep=False)]",
45: "result = orders[orders.duplicated(['customer_id','product'], keep=False)]",
46: "result = orders.drop_duplicates()",
47: "result = orders.loc[orders.duplicated('order_id', keep=False),'revenue'].sum()",
48: "result = orders.pivot_table(index='city', columns='category', values='revenue', aggfunc='sum', fill_value=0)",
49: "result = orders.pivot_table(index='city', columns='status', values='order_id', aggfunc='count', fill_value=0)",
50: "result = orders.assign(month=orders.order_date.dt.to_period('M')).pivot_table(index='channel', columns='month', values='revenue', aggfunc='sum', fill_value=0)",
51: "result = orders.pivot_table(index='city', values=['order_id','revenue'], aggfunc={'order_id':['count'],'revenue':['sum']})",
52: "pivot = orders.pivot_table(index='city', columns='category', values='revenue', aggfunc='sum', fill_value=0)\nresult = pivot.reset_index().melt(id_vars='city', var_name='category', value_name='revenue')",
53: "result = orders.groupby(orders.order_date.dt.to_period('M')).revenue.sum()",
54: "result = orders.groupby(orders.order_date.dt.dayofweek.ge(5)).revenue.sum().rename(index={False:'Будни',True:'Выходные'})",
55: "daily = orders.groupby('order_date').revenue.sum()\nresult = daily[daily == daily.max()]",
56: "daily = orders.groupby('order_date').revenue.sum()\nresult = pd.DataFrame({'daily_revenue':daily, 'cumulative_revenue':daily.cumsum()})",
57: "result = orders[orders.order_date >= orders.order_date.max() - pd.Timedelta(days=6)]",
58: "result = orders.merge(customers[['customer_id','customer_name','loyalty_level']], on='customer_id', how='left', validate='many_to_one')",
59: "result = orders.merge(products[['product','brand','cost_price']], on='product', how='left', validate='many_to_one')",
60: "joined = orders.merge(customers[['customer_id']], on='customer_id', how='left', indicator=True)\nresult = joined[joined._merge == 'left_only']",
61: "result = (len(orders.merge(customers, on='customer_id', how='inner')), len(orders.merge(customers, on='customer_id', how='left')))",
62: "joined = orders.merge(managers[['manager','experience_years']], on='manager', how='left', validate='many_to_one')\nresult = joined.groupby('experience_years').revenue.sum()",
63: "result = orders.assign(category=orders.category.str.lower())",
64: "result = orders[orders['product'].str.contains('монитор', case=False, na=False)]",
65: "result = orders.channel.str[:3].str.upper()",
66: "result = orders[orders['product'] != orders['product'].str.strip()]",
67: "result = orders['product'].str[0].value_counts()",
68: "result = orders.status.map({'Оплачен':'paid','Отменён':'cancelled','Возврат':'returned'})",
69: "counts = orders.groupby('customer_id').order_id.nunique()\nresult = counts.apply(lambda count: 'Новый' if count == 1 else 'Постоянный' if count == 2 else 'VIP')",
70: "result = orders.rating.map({5:'Отлично',4:'Хорошо',3:'Проблема',2:'Проблема',1:'Проблема'}).fillna('Нет оценки')",
71: "result = pd.cut(orders.price, bins=[-float('inf'),3000,10000,float('inf')], right=False, labels=['Бюджетный','Средний','Дорогой'])",
72: "result = (orders.discount / (orders.revenue + orders.discount) * 100).round(1)",
73: "result = orders.groupby('city').revenue.sum().sort_values(ascending=False).plot.bar(title='Выручка по городам', xlabel='Город', ylabel='Выручка, руб.')",
74: "result = orders.groupby('order_date').revenue.sum().plot.line(marker='o', title='Дневная выручка', xlabel='Дата', ylabel='Выручка, руб.')",
75: "import matplotlib.pyplot as plt\nfigure, axes = plt.subplots(1,2,figsize=(10,4))\norders.groupby('channel').order_id.count().plot.bar(ax=axes[0], title='Заказы по каналам', xlabel='Канал', ylabel='Заказы')\norders.groupby('channel').revenue.sum().plot.bar(ax=axes[1], title='Выручка по каналам', xlabel='Канал', ylabel='Выручка, руб.')\nfigure.tight_layout()\nresult = figure",
76: "result = orders.delivery_days.plot.hist(bins=[-0.5,0.5,1.5,2.5,3.5,4.5,5.5], title='Распределение доставки', xlabel='Дни доставки', ylabel='Заказы')",
77: "ratings = orders.groupby('category').rating.mean().round(2)\ncolors = ['red' if value == ratings.min() else 'steelblue' for value in ratings]\nresult = ratings.plot.bar(color=colors, title='Средняя оценка категорий', xlabel='Категория', ylabel='Средняя оценка')",
78: "result = orders.assign(cancelled=orders.status.eq('Отменён')).groupby('city').agg(order_count=('order_id','count'), total_revenue=('revenue','sum'), avg_revenue=('revenue','mean'), cancelled_pct=('cancelled',lambda s:s.mean()*100), avg_delivery_days=('delivery_days','mean'))",
79: "result = orders.assign(cancelled=orders.status.eq('Отменён')).groupby('channel').agg(cancelled_pct=('cancelled',lambda s:s.mean()*100), avg_delivery_days=('delivery_days','mean'))\nresult['is_problem'] = result.cancelled_pct.eq(result.cancelled_pct.max())",
80: "profiles = orders.groupby('customer_id').agg(order_count=('order_id','nunique'), total_revenue=('revenue','sum'))\nleader = profiles.sort_values('total_revenue', ascending=False).head(1).reset_index()\nresult = leader.merge(customers[['customer_id','customer_name','home_city']], on='customer_id', how='left')[['customer_id','customer_name','home_city','order_count','total_revenue']]",
81: "joined = orders.merge(products[['product','cost_price']], on='product', how='left', validate='many_to_one')\nresult = joined.assign(gross_profit=joined.revenue - joined.cost_price * joined.quantity).groupby('category').gross_profit.sum()",
82: "city_totals = orders.groupby('city').revenue.sum()\nchannel_totals = orders.groupby('channel').revenue.sum()\ncategory_totals = orders.groupby('category').revenue.sum()\ncancelled = orders.status.eq('Отменён').sum()\nslow = orders.delivery_days.gt(3).sum()\nresult = pd.DataFrame([['Города', f'{city_totals.idxmax()}: выручка — {city_totals.max()} рублей', city_totals.max()], ['Каналы', f'{channel_totals.idxmax()}: выручка — {channel_totals.max()} рублей', channel_totals.max()], ['Категории', f'{category_totals.idxmax()}: выручка — {category_totals.max()} рублей', category_totals.max()], ['Отмены', f'Отменённых заказов — {cancelled}', cancelled], ['Доставка', f'Доставок дольше трёх дней — {slow}', slow]], columns=['topic','statement','value'])",
83: "SELECT * FROM orders WHERE status = 'Оплачен' AND revenue > 10000 ORDER BY revenue DESC",
84: "SELECT city, SUM(revenue) AS total_revenue FROM orders GROUP BY city",
85: "SELECT channel, COUNT(*) AS orders_count, SUM(revenue) AS total_revenue, ROUND(AVG(revenue),2) AS average_order FROM orders GROUP BY channel",
86: "SELECT customer_id, COUNT(DISTINCT order_id) AS orders_count FROM orders GROUP BY customer_id HAVING COUNT(DISTINCT order_id) >= 2 ORDER BY orders_count DESC",
87: "SELECT channel, ROUND(100.0 * SUM(CASE WHEN status = 'Отменён' THEN 1 ELSE 0 END) / COUNT(*),1) AS cancelled_pct FROM orders GROUP BY channel",
88: "WITH ranked AS (SELECT city, order_id, revenue, ROW_NUMBER() OVER (PARTITION BY city ORDER BY revenue DESC) AS rank_in_city FROM orders) SELECT * FROM ranked WHERE rank_in_city <= 3 ORDER BY city, rank_in_city",
89: "WITH monthly AS (SELECT substr(order_date,1,7) AS month, SUM(revenue) AS total_revenue FROM orders GROUP BY month) SELECT month, total_revenue, LAG(total_revenue) OVER (ORDER BY month) AS previous_revenue, total_revenue-LAG(total_revenue) OVER (ORDER BY month) AS revenue_change FROM monthly ORDER BY month",
90: "WITH city_summary AS (SELECT city, COUNT(*) AS orders_count, SUM(revenue) AS total_revenue, AVG(revenue) AS average_order FROM orders GROUP BY city) SELECT * FROM city_summary WHERE total_revenue > 100000",
91: "SELECT orders.*, customers.customer_name, customers.loyalty_level FROM orders LEFT JOIN customers ON orders.customer_id = customers.customer_id",
92: "WITH joined AS (SELECT orders.*, customers.customer_name FROM orders LEFT JOIN customers ON orders.customer_id = customers.customer_id) SELECT (SELECT COUNT(*) FROM orders) AS rows_before, (SELECT COUNT(DISTINCT order_id) FROM orders) AS unique_orders_before, (SELECT SUM(revenue) FROM orders) AS revenue_before, COUNT(*) AS rows_after, COUNT(DISTINCT order_id) AS unique_orders_after, SUM(revenue) AS revenue_after FROM joined",
}
assert set(REFERENCES) == set(range(1,93))
