import { useEffect, useState } from 'react';
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../auth';
import { modulesQ } from '../queries';
import { currentJournalOwner, diagnosticKind, diagnosticGuidance, diagnosticDescription, diagnosticSignature, loadRunFailures, sandboxCodeKey, type HistoryRecord } from '../attempt-journal';
import { loadTaskState, saveTaskState } from '../task-storage';
import type { KnowledgeUnit } from '../types';
import './contextual-history.css';
type HistoryPage = { items: HistoryRecord[]; has_more: boolean; next_offset: number | null };
const date = (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('ru') : 'Дата неизвестна';
const recordKey = (record: HistoryRecord) => `${record.source ? 'run' : 'attempt'}:${record.id}`;
export function AttemptHistory({ errors = false }: { errors?: boolean }) {
 const { user } = useAuth(), ownerId = user?.id ?? null;
 const [search, setSearch] = useSearchParams(), nav = useNavigate();
 const [, refreshLocal] = useState(0), [notice, setNotice] = useState(''), [restoreKey, setRestoreKey] = useState<string | null>(null);
 useEffect(() => { const refresh = () => refreshLocal(value => value + 1); window.addEventListener('koda-run-observations', refresh); window.addEventListener('storage', refresh); return () => { window.removeEventListener('koda-run-observations', refresh); window.removeEventListener('storage', refresh); }; }, []);
 const history = useInfiniteQuery({ queryKey: ['attempt-history', ownerId], initialPageParam: 0, queryFn: ({ pageParam }) => api<HistoryPage>(`/attempts/history?offset=${pageParam}&limit=30`), getNextPageParam: page => page.next_offset ?? undefined });
 const modules = useQuery({ queryKey: ['modules'], queryFn: modulesQ });
 const units = useQuery({ queryKey: ['knowledge'], queryFn: () => api<KnowledgeUnit[]>('/knowledge') });
 const records = [...(history.data?.pages.flatMap(page => page.items) ?? []), ...loadRunFailures(ownerId)].sort((a,b) => Date.parse(b.created_at)-Date.parse(a.created_at));
 const status=search.get('status')??'all', mode=search.get('mode')??'all', text=search.get('q')??'';
 const exercises=modules.data?.flatMap(module=>module.topics.flatMap(topic=>topic.exercises))??[];
 const taskFor=(record:HistoryRecord)=>exercises.find(task=>task.id===record.task_id);
 const matches=(record:HistoryRecord)=>(!errors||!record.passed)&&(status==='all'||(status==='passed')===record.passed)&&(mode==='all'||record.feedback?.mode===mode)&&`${taskFor(record)?.title??record.task_id} ${record.feedback?.error??''}`.toLocaleLowerCase('ru').includes(text.toLocaleLowerCase('ru'));
 const filtered=records.filter(matches);
 const groups=new Map<string,HistoryRecord[]>(); filtered.forEach(record=>{const signature=diagnosticSignature(record);groups.set(signature,[...(groups.get(signature)??[]),record]);});
 const displayed=errors?[...groups.values()].map(group=>group[0]):filtered;
 const wantedKey=search.get('record');
 const directId=wantedKey?.startsWith('attempt:')?wantedKey.slice(8):null;
 const direct=useQuery({queryKey:['attempt-history-direct',ownerId,directId],queryFn:()=>api<HistoryRecord>(`/attempts/history/${encodeURIComponent(directId!)}`),enabled:Boolean(directId)});
 const selected=wantedKey?filtered.find(record=>recordKey(record)===wantedKey)??(direct.data?.id===directId&&matches(direct.data)?direct.data:undefined):displayed[0], selectedKey=selected?recordKey(selected):null;
 const detail=useQuery({queryKey:['attempt-history-detail',ownerId,selected?.id],queryFn:()=>api<HistoryRecord>(`/attempts/history/${encodeURIComponent(selected!.id)}`),enabled:Boolean(selected&&!selected.source)});
 const full=selected?.source?selected:detail.data?.id===selected?.id?detail.data:undefined;
 const task=selected?taskFor(selected):undefined, unit=task?units.data?.find(item=>item.id===task.knowledge_unit_id):undefined;
 const occurrences=selected?groups.get(diagnosticSignature(selected))??[selected]:[];
 useEffect(()=>{setRestoreKey(null);setNotice('');},[ownerId,selectedKey]);
 const confirmRestore=restoreKey===`${ownerId}:${selectedKey}`;
 const change=(key:string,value:string)=>{const next=new URLSearchParams(search);if(value)next.set(key,value);else next.delete(key);if(key!=='record')next.delete('record');setSearch(next);setNotice('');setRestoreKey(null);};
 const restore=()=>{if(!full||typeof full.code!=='string'||currentJournalOwner()!==ownerId)return;const previous=full.task_id==='sandbox'?localStorage.getItem(sandboxCodeKey(ownerId)):loadTaskState(full.task_id)?.code;if(previous!==undefined&&previous!==null&&previous!==full.code&&!confirmRestore){setRestoreKey(`${ownerId}:${selectedKey}`);return;}if(full.task_id==='sandbox')localStorage.setItem(sandboxCodeKey(ownerId),full.code);else if(task)saveTaskState(full.task_id,{code:full.code});else return;nav(full.task_id==='sandbox'?'/sandbox':`/practice/${encodeURIComponent(full.task_id)}`);};
 return <section className="page history-page"><header><small>{errors?'РАЗБОР':'ВАШ ПУТЬ'}</small><h1>{errors?'Разобраться и продолжить':'История решений'}</h1><p>{errors?'Сообщение, ваш код и следующий шаг — рядом.':'Проверенные решения и неудачные запуски на этом устройстве. Время выполнения кода не равно времени занятия.'}</p></header><div className="context-page-layout"><div className="context-main">
 {modules.isError&&<div role="alert"><p>Каталог задач недоступен. Переход и восстановление пока отключены.</p><button onClick={()=>modules.refetch()}>Повторить загрузку задач</button></div>}{units.isError&&<div role="alert"><p>Материалы для разбора не загрузились.</p><button onClick={()=>units.refetch()}>Повторить загрузку материалов</button></div>}<div className="history-filters"><label>Поиск<input value={text} onChange={event=>change('q',event.target.value)} placeholder="Задача или сообщение"/></label><label>Режим<select value={mode} onChange={event=>change('mode',event.target.value)}><option value="all">Все режимы</option><option value="python">Python</option><option value="sql">SQL</option><option value="excel">Excel</option><option value="power-bi">Power BI</option></select></label>{!errors&&<label>Результат<select value={status} onChange={event=>change('status',event.target.value)}><option value="all">Все результаты</option><option value="passed">Решено</option><option value="failed">Не завершено</option></select></label>}</div>
 {history.isPending&&<p role="status">Загружаем историю решений…</p>}{history.isError&&<div role="alert"><p>Историю проверок загрузить не удалось. Локальные запуски показаны отдельно.</p><button onClick={()=>history.refetch()}>Повторить загрузку истории</button></div>}
 {!displayed.length&&!history.isPending&&<p className="context-card">{errors?'Ошибок по этим условиям пока нет.':'Записей по этим условиям пока нет.'}</p>}
 <div className="history-list" style={{order:3}}>{displayed.map(record=><button className={(errors&&selected&&diagnosticSignature(selected)===diagnosticSignature(record))||selectedKey===recordKey(record)?'selected':''} key={recordKey(record)} onClick={()=>change('record',recordKey(record))}><span><strong>{errors?record.error_type??'Проверка решения':taskFor(record)?.title??(record.task_id==='sandbox'?'Песочница':record.task_id)}</strong><small>{date(record.created_at)} · {diagnosticKind(record)==='system'?'Сбой среды':record.source?'Запуск · на этом устройстве':record.passed?'Решено':'Проверка не пройдена'}</small></span>{errors&&<small>{groups.get(diagnosticSignature(record))?.length} случаев в загруженной истории</small>}</button>)}</div>
 {history.hasNextPage&&<button disabled={history.isFetchingNextPage} onClick={()=>history.fetchNextPage()}>{history.isFetchingNextPage?'Загружаем…':'Загрузить ещё'}</button>}
 {directId&&direct.isPending&&<p role="status">Загружаем выбранную запись…</p>}{directId&&direct.isError&&<div role="alert"><p>Выбранная запись недоступна.</p><button onClick={()=>direct.refetch()}>Повторить загрузку записи</button></div>}{wantedKey&&!selected&&!direct.isPending&&!direct.isError&&<p role="status">Запись не найдена в загруженной истории или не соответствует фильтрам. Загрузите ещё записи либо сбросьте фильтры.</p>}
 {selected&&<article className="context-card history-detail" style={{order:2}} key={`${ownerId}:${selectedKey}`}><small>{selected.source?'НА ЭТОМ УСТРОЙСТВЕ · ЗАПУСК':'СОХРАНЁННАЯ ПРОВЕРКА'}</small><h2>{errors?selected.error_type??'Проверка решения':task?.title??'Подробности записи'}</h2><p>{date(selected.created_at)}</p>{errors&&occurrences.length>1&&<label>Где встречалась ошибка<select value={selectedKey??''} onChange={event=>change('record',event.target.value)}>{occurrences.map(record=><option key={recordKey(record)} value={recordKey(record)}>{date(record.created_at)} · {record.source?'Запуск':'Проверка'}</option>)}</select></label>}
 {!selected.source&&detail.isPending&&<p role="status">Загружаем код этой попытки…</p>}{detail.isError&&<div role="alert"><p>Подробности не загрузились.</p><button onClick={()=>detail.refetch()}>Повторить загрузку подробностей</button></div>}
 {full&&<><p>{full.passed?"Решено":diagnosticKind(full)==="system"?"Сбой среды":full.source?"Неудачный запуск":"Проверка не пройдена"} · Выполнение кода: {full.execution_ms} мс</p>{!full.passed&&records.some(record=>record.task_id===full.task_id&&record.passed&&Date.parse(record.created_at)>Date.parse(full.created_at))&&<p>После этого задача решена. Эта ошибка сохранена для разбора.</p>}<h3>{full.passed?'Решение прошло проверку':'Что произошло'}</h3>{!full.passed&&<><p>{diagnosticDescription(full)}</p>{full.feedback?.error&&<pre className="history-message">{full.feedback.error}</pre>}</>}<p>Где: {task?.title??(full.task_id==='sandbox'?'Песочница':'Задача вне текущего каталога')} · {full.feedback?.mode??'Режим не сохранён'}</p>{full.feedback?.line&&full.code&&full.feedback.line<=full.code.split('\n').length?<p>Строка {full.feedback.line}: <code>{full.code.split('\n')[full.feedback.line-1]}</code></p>:!full.passed&&<p className="history-muted">Точная строка ошибки не определена.</p>}{full.feedback?.explanation?.difference&&<p>Разница: {full.feedback.explanation.difference}</p>}{full.feedback?.explanation?.expected&&<div><h3>Ожидалось</h3><pre className="history-message">{full.feedback.explanation.expected}</pre></div>}{full.feedback?.explanation?.actual&&<div><h3>Получено</h3><pre className="history-message">{full.feedback.explanation.actual}</pre></div>}<h3>Ваш код в этой попытке</h3>{typeof full.code==='string'?<pre className="history-code">{full.code}</pre>:<p>Код не сохранён.</p>}{typeof full.code==='string'&&<button onClick={async()=>{if(typeof full.code!=='string')return;try{await navigator.clipboard.writeText(full.code);if(currentJournalOwner()===ownerId)setNotice('Код скопирован');}catch{if(currentJournalOwner()===ownerId)setNotice('Не удалось скопировать код. Выделите его вручную.');}}}>Скопировать код</button>}</>}
 </article>}
 </div><aside className="context-aside" aria-label={errors?'Помощь с ошибкой':'Действия с записью'}><section className="context-card"><h2>{errors?'Как разобраться':'Вернуться к работе'}</h2>{!selected?<p>Выберите запись слева.</p>:<><p>{task?.title??(selected.task_id==='sandbox'?'Песочница':'Задача вне текущего каталога')}</p>{errors&&full&&<ol>{diagnosticGuidance(full).map((step,index)=><li key={index}>{step}</li>)}</ol>}{unit&&<Link to={`/knowledge/${unit.slug}`}>Разобрать тему: {unit.title} →</Link>}{task&&<Link to={`/practice/${encodeURIComponent(task.id)}`}>Открыть задачу →</Link>}{selected.task_id==='sandbox'&&<Link to="/sandbox">Открыть песочницу →</Link>}{typeof full?.code==='string'&&(task||selected.task_id==='sandbox')&&<button onClick={restore}>Восстановить код</button>}{confirmRestore&&<div role="alert"><p>Текущий черновик отличается. Заменить его кодом выбранной попытки? Статус выполнения сохранится.</p><button onClick={restore}>Заменить черновик</button><button onClick={()=>setRestoreKey(null)}>Отмена</button></div>}<small>Открытие задачи сохраняет текущий черновик. Восстановление заменяет только код.</small></>}{notice&&<p role="status">{notice}</p>}</section></aside></div></section>;
}
