import { useEffect, useRef, useState } from "react";
import { KodaButton, KodaIcon, KodaIconButton, kodaIconNames } from "../ui";
export function DesignSystem() {
  const [search, setSearch] = useState("");
  const [hint, setHint] = useState(false);
  const [busy, setBusy] = useState(false);
  const [output, setOutput] = useState("Выберите действие, чтобы посмотреть состояние интерфейса.");
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => clearTimeout(timer.current), []);
  const run = () => {
    if (busy) return;
    setBusy(true); setOutput("Демонстрация запуска…");
    timer.current = setTimeout(() => { setBusy(false); setOutput("Запуск завершён. Это локальная демонстрация интерфейса: Python не выполнялся."); }, 900);
  };
  const names = kodaIconNames.filter(name => name.toLowerCase().includes(search.toLowerCase()));
  return <div className="koda-ui koda-kit">
    <header className="kit-top"><div className="kit-brand"><span>K</span><strong>KODA</strong></div><span className="kit-badge">UI Kit · демо без сохранения</span></header>
    <main className="kit-body">
      <section className="kit-intro"><p className="kit-eyebrow">DESIGN SYSTEM / 01</p><h1>Soft Line</h1><p>Спокойный интерфейс для сосредоточенной практики. Оригинальные иконки, понятные действия и состояния, которые не отвлекают от задачи.</p></section>
      <section className="kit-section"><div className="kit-section-heading"><h2>01 — Иконки</h2><span>24 × 24 · линия 1.65 · размеры 16 / 20 / 24</span></div><label className="kit-search"><KodaIcon name="Search" /><input aria-label="Поиск иконок" value={search} onChange={event => setSearch(event.target.value)} placeholder="Найти иконку по имени, например Hint" />{search && <KodaIconButton icon="Close" label="Очистить поиск" onClick={() => setSearch("")} />}</label><div className="kit-icon-grid">{names.map(name => <div className="kit-icon-tile" key={name}><div className="kit-icon-sizes"><KodaIcon name={name} size={16} /><KodaIcon name={name} size={20} /><KodaIcon name={name} size={24} /></div><strong>{name}</strong></div>)}{names.length === 0 && <p className="kit-empty">Иконки не найдены.</p>}</div></section>
      <section className="kit-section"><div className="kit-section-heading"><h2>02 — Действия</h2><span>Высота 44 · радиус 12 · иконка 20</span></div><div className="kit-panel"><div className="kit-button-row"><KodaButton variant="secondary" icon="Run" onClick={run} loading={busy} loadingLabel="Запуск выполняется">Запустить</KodaButton><KodaButton icon="Check" onClick={() => setOutput("Демонстрация проверки. Правильность кода не оценивалась.")}>Проверить</KodaButton><KodaButton variant="quiet" icon="Hint" aria-pressed={hint} onClick={() => setHint(value => !value)}>Подсказка</KodaButton><KodaButton variant="danger" icon="Reset" onClick={() => { clearTimeout(timer.current); setBusy(false); setHint(false); setOutput("Демонстрация сброшена."); }}>Сбросить демо</KodaButton></div></div><div className="kit-state-grid"><div className="kit-panel"><h3>Загрузка</h3><KodaButton icon="Save" loading loadingLabel="Сохранение выполняется">Сохранить</KodaButton><p role="status">Сохранение выполняется…</p><p>Размер кнопки остаётся прежним. Повторное нажатие блокируется.</p></div><div className="kit-panel"><h3>Недоступное действие</h3><KodaButton variant="secondary" icon="Check" disabled aria-describedby="kit-disabled-reason">Проверить</KodaButton><p id="kit-disabled-reason">Недоступно: в демонстрационном примере ещё нет кода для проверки.</p></div><div className="kit-panel"><h3>Только иконка</h3><div className="kit-button-row"><KodaIconButton icon="Hint" label="Показать подсказку" aria-pressed={hint} onClick={() => setHint(value => !value)} /><KodaIconButton icon="Reset" label="Сбросить результат" onClick={() => setOutput("Результат сброшен.")} /><KodaIconButton icon="Search" label="Перейти к поиску иконок" onClick={() => document.querySelector<HTMLInputElement>('input[aria-label="Поиск иконок"]')?.focus()} /></div><p>У каждой кнопки есть доступное имя и область нажатия 44 × 44.</p></div></div></section>
      <section className="kit-section"><div className="kit-section-heading"><h2>03 — В контексте</h2><span>Живой пример · только локальное состояние</span></div><div className="kit-panel kit-example"><div><h3>Одно действие — понятный результат</h3><p>Попробуйте запуск, проверку и подсказку. Пример не выполняет Python, не отправляет запросы и не меняет учебный прогресс.</p><div className="kit-button-row"><KodaButton variant="secondary" icon="Run" loading={busy} onClick={run}>Запустить пример</KodaButton><KodaButton icon="Check" disabled={busy} onClick={() => setOutput("Проверка завершена: демонстрация интерфейса. Правильность кода не оценивалась.")}>Проверить пример</KodaButton></div>{hint && <div className="kit-hint">Подсказка открыта. Её можно закрыть повторным нажатием кнопки «Подсказка».</div>}</div><div className="kit-output" role="status" aria-live="polite"><h3>Результат</h3><p>{output}</p></div></div></section>
      <footer className="kit-tokens"><span><i className="kit-swatch" style={{ background: "#426b54" }} />Forest · #426B54</span><span><i className="kit-swatch" style={{ background: "#eef4ef" }} />Sage · #EEF4EF</span><span><i className="kit-swatch" style={{ background: "#cbd8ce" }} />Border · #CBD8CE</span><a className="kit-link" href="/design-prototype">Открыть макет приложения</a></footer>
    </main>
  </div>;
}
